In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [3]:
# data = pd.read_excel("data_test-1.xls", header=26, skiprows=0)
data = pd.read_excel("python_data.xls")

In [4]:
data.head()

,Lease,Space,Product Category,Space Type,Unnamed: 4,Unnamed: 5,Shop Count 2014,Area 2014,MAT $,MAT $ (Last Year),...,Forecasted Sales-Calc,PA Commencement Date-entry,Unnamed: 146,NPV,NPV PSF,Capital Calculated,Unnamed: 150,Operational and Developmental Tenant Allowances,Promotional Allowance,Defaulted
0,45252,0112230 G011,SF21 US Food Service,"In-Line Units 0-9,999 SF",NaN,12230 G011 Hot Dog on a Stick,1,532,537980.00,515426.00,...,533290.6,NaN,NaN,498376.3,936.7976,0,NaN,0,0,1
1,62599,0112229 9270,SF21 US Food Service,"Kiosk 0-9,999 SF",NaN,12229 9270 Hot Dog on a Stick,1,260,225449.01,235559.00,...,224231.3,NaN,NaN,3907.235,15.02783,0,NaN,0,0,1
2,37247,0112234 1000,SF21 US Food Service,"In-Line Units 0-9,999 SF",NaN,12234 1000 Hot Dog on a Stick,0,0,22000.00,211611.00,...,22000,NaN,NaN,0,0,0,NaN,0,0,1
3,27469,0112243 O358,SF11 US Food Court,"Food Court 0-9,999 SF",NaN,12243 O358 Hot Dog on a Stick,0,0,13407.00,167542.22,...,13407,NaN,NaN,0,0,0,NaN,0,0,1
4,86698,0112247 0584,SF11 US Food Court,"Food Court 0-9,999 SF",NaN,12247 0584 Hot Dog on a Stick,1,555,295902.67,299918.00,...,273029.8,NaN,NaN,186406.4,335.8674,0,NaN,0,-56916,1

In [7]:
# merchant_types.sort()  #revise sort function largest to smallest
# merchant_types
# merchant_types.sort?

data.shape

(2561, 154)

In [8]:
# merchant_types = data.groupby(['merchant_type'])['2015_area'].sum()
# merchant_types.sort(ascending=False)  #revise sort function largest to smallest
# plt.xticks(np.arange(len(merchant_types)), rotation='vertical')
# merchant_types[:10].plot(color='r', marker='o', figsize=(50, 20))

In [59]:
data['merchant_type'].plot

<bound method Series.plot_series of 0                     S132 US Teens Fashion
1                     S132 US Teens Fashion
2                    S131 US Unisex Fashion
3                      S231 US Family Shoes
4                     S132 US Teens Fashion
5                   S521 US Beauty & Health
6                      SF21 US Food Service
7                     S211 US Women's Shoes
8                     S211 US Women's Shoes
9                          Z111 US Not used
10                  S111 US Women's Fashion
11                  S111 US Women's Fashion
12              S153 US Fashion Accessories
13        S472 US Gifts, Cards & Stationery
14        S472 US Gifts, Cards & Stationery
15                   S131 US Unisex Fashion
16                  S521 US Beauty & Health
17                  S111 US Women's Fashion
18                       SF31 US Restaurant
19                       SF31 US Restaurant
20                    S211 US Women's Shoes
21                       SF11 US Food Court
22      S141 US Clothing Sundry - Childrens
23      S141 US Clothing Sundry - Childrens
24              S153 US Fashion Accessories
25              S153 US Fashion Accessories
26      S141 US Clothing Sundry - Childrens
27                     S311 US Fine Jewelry
28                  S521 US Beauty & Health
29               S441 US Sports Specialties
                       ...
2395                S521 US Beauty & Health
2396                S521 US Beauty & Health
2397             S441 US Sports Specialties
2398             S441 US Sports Specialties
2399             S441 US Sports Specialties
2400             S441 US Sports Specialties
2401                   SF21 US Food Service
2402                   SF21 US Food Service
2403                   SF21 US Food Service
2404                   PP96 US In-line (MM)
2405                S111 US Women's Fashion
2406                   PP96 US In-line (MM)
2407                S521 US Beauty & Health
2408            S153 US Fashion Accessories
2409                   SF21 US Food Service
2410                  S211 US Women's Shoes
2411                   SF21 US Food Service
2412                      M166 US Nordstrom
2413                 S131 US Unisex Fashion
2414                 S131 US Unisex Fashion
2415                     SF31 US Restaurant
2416                S521 US Beauty & Health
2417                S521 US Beauty & Health
2418      S472 US Gifts, Cards & Stationery
2419                 S832 US Service Trades
2420                 S832 US Service Trades
2421                  S211 US Women's Shoes
2422      S472 US Gifts, Cards & Stationery
2423           S491 US Miscellaneous Trades
2424                   S231 US Family Shoes
Name: merchant_type, dtype: object>